apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: []

    rule_files:
      - /etc/prometheus/alerts.yml

    scrape_configs:
      # Scrape Prometheus itself
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      # Scrape backend dev
      - job_name: reclamation-backend-dev
        metrics_path: /api/actuator/prometheus
        static_configs:
          - targets: ['dev-backend-service.reclamation-dev.svc.cluster.local:8080']

      # Scrape backend staging
      - job_name: reclamation-backend-staging
        metrics_path: /api/actuator/prometheus
        static_configs:
          - targets: ['staging-backend-service.reclamation-staging.svc.cluster.local:8080']

      # Scrape backend prod
      - job_name: reclamation-backend-prod
        metrics_path: /api/actuator/prometheus
        static_configs:
          - targets: ['prod-backend-service.reclamation-prod.svc.cluster.local:8080']
