apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: reclamation-prod
data:
  datasource-url: "jdbc:mysql://prod-mysql-service:3306/reclamation_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
