apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reclamation-prod


namePrefix: prod-

commonLabels:
  environment: prod

images:
- name: gcr.io/certain-reducer-493511-v6/reclamation-backend
  newName: gcr.io/certain-reducer-493511-v6/reclamation-backend
  newTag: f889718b8c3d86b0ab54ac936c087e1a509634a0
- name: gcr.io/certain-reducer-493511-v6/reclamation-frontend
  newName: gcr.io/certain-reducer-493511-v6/reclamation-frontend
  newTag: f889718b8c3d86b0ab54ac936c087e1a509634a0

patches:
- path: patches.yaml

resources:
- hpa.yaml
- backend-configmap.yaml
- ../../base

secretGenerator:
- literals:
  - root-password=prod_STRONG_password_789!
  name: mysql-secret
  options:
    disableNameSuffixHash: true
