apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reclamation-prod


namePrefix: prod-

commonLabels:
  environment: prod

images:
- name: gcr.io/certain-reducer-493511-v6/reclamation-backend
  newName: gcr.io/certain-reducer-493511-v6/reclamation-backend
  newTag: 90e96c162fe90a2da5f31100bbcf2bf13bffb19c
- name: gcr.io/certain-reducer-493511-v6/reclamation-frontend
  newName: gcr.io/certain-reducer-493511-v6/reclamation-frontend
  newTag: 90e96c162fe90a2da5f31100bbcf2bf13bffb19c

patches:
- path: patches.yaml

resources:
- hpa.yaml
- backend-configmap.yaml
- ../../base

secretGenerator:
- literals:
  - root-password=prod_STRONG_password_789!
  name: mysql-secret
  options:
    disableNameSuffixHash: true
