apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reclamation-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

images:
  - name: gcr.io/certain-reducer-493511-v6/reclamation-backend
    newTag: v9
  - name: gcr.io/certain-reducer-493511-v6/reclamation-frontend
    newTag: v2

patches:
  - path: patches.yaml

resources:
  - backend-configmap.yaml

secretGenerator:
  - name: mysql-secret
    literals:
      - root-password=dev_password_123
    options:
      disableNameSuffixHash: true
